const apiCode = {
    // Global
    "global-e-01": "Giá trị không hợp lệ",
    "permission-01-01": "Không có quyền thực thi",
    // Auth
    "auth-s-01": "Yêu cầu đăng ký thành công, hãy kiểm tra email của bạn",
    "auth-f-01-01": "Email đã tồn tại",
    "auth-f-02-01": "Mã không hợp lệ",
    "auth-s-03": "Đăng ký thành công, Chào mừng bạn quay lại với WORK-ERP",
    "auth-f-03": "Hết phiên đăng nhập",
    "auth-s-04": "Đã làm mưới access token",
    "auth-s-05": "Đăng xuất thành công",
    "auth-s-06": "Đổi mật khẩu thành công",
    "auth-s-08": "Yêu cầu lấy lại mật khẩu thành công",
    "auth-s-09": "Lấy lại mật khẩu thành công",
    "auth-f-09-01": "Mã xác thực không hợp lệ",
    "auth-s-10": "Lấy thông tin của bạn thành công",
    // User
    "user-s-01": "Không tìm thấy tài khoản với email",
    "user-s-02": "Tạo người dùng thành công",
    "user-s-03": "Kiểm tra đăng nhập thành công",
    "user-s-04": "Lấy thông tin người dùng thành công",
    "user-s-05": "Đổi mật khẩu thành công",
    "user-s-06": "Đăng nhập Oauth2 thành công",
    "user-s-07": "Lấy mật khẩu mới thành công",
    "user-s-08": "Lấy thông tin người dùng thành công",
    "user-f-02-01": "Không tim thấy người dùng",
    "user-f-03-01": "Không tim thấy người dùng",
    "user-f-03-02": "Sai mật khẩu",
    "user-f-04-01": "Không tim thấy người dùng",
    "user-f-05-01": "Không tim thấy người dùng",
    "user-f-05-02": "Sai mật khẩu cũ",
    "user-f-08-01": "Không tìm thấy email",
    "user-f-09-01": "Không tim thấy người dùng",
    // Util
    "util-upload-s-01": "Tải lên một ảnh thành công",
    "util-upload-s-02": "Tải lên nhiều ảnh thành công",
    "util-upload-s-03": "Tải lên video thành công",
    "util-upload-s-04": "Xóa file thành công",
    "util-upload-f-01": "Tải lên một ảnh không thành công",
    "util-upload-f-02": "Tải lên nhiều ảnh không thành công",
    "util-upload-f-03-01": "Dung lượng phải nhỏ hơn 50MB",
    "util-upload-f-03-02": "Tải lên video thành công",
    "util-upload-f-04": "Xóa file không thành công",
    // Company
    "company_app-company-s-01": "Tạo công ty mới thành công",
    "company_app-company-s-02": "Lấy thông tin công ty thành công",
    "company_app-company-s-03": "Cập nhật modules cho công ty thành công",
    "company_app-company-s-04": "Lấy tất cả công ty tôi làm việc thành công",
    "company_app-company-s-05": "Cập nhật thông tin công ty thành công",
    "company_app-company-f-02-01": "Không tìm thấy công ty",
    "company_app-company-f-03-01": "Không tìm thấy công ty",
    "company_app-company-f-05-01": "Không tìm thấy công ty",
    "company_app-module-f-01-01": "Module với code đã tồn tại rồi",
    "company_app-module-s-01": "Tạo module mới thành công",
    "company_app-module-s-02": "Lấy tất cả module thành công",
    "company_app-cmr-s-01": "Lấy tất cả CMR thành công",
    "company_app-cmr-s-02": "Lấy CMR của employee thành công",
    "company_app-cmr-s-03": "Cập nhật CMR thành công",
    "company_app-cmr-f-02-01": "Không tìm thấy công ty",
    "company_app-cmr-f-03-01": "Không tìm thấy công ty",
    // HR
    "hr_app-ctr-s-01": "Tạo mới hợp đồng mới thành công",
    "hr_app-ctr-s-02": "Cập nhật hợp đồng thành công",
    "hr_app-ctr-s-03": "Xóa hợp đồng thành công",
    "hr_app-ctr-s-04": "Lấy hợp đông của nhân viên thành công",
    "hr_app-ctr-s-05": "Lấy hợp đồng của tôi thành công",
    "hr_app-ctr-f-02-01": "Không tìm thấy hợp đồng",
    "hr_app-ctr-f-03-01": "Không tìm thấy hợp đồng",
    "hr_app-ctr-f-05-01": "Không tìm thấy nhân viên",
    "hr_app-dpm-s-01": "Tạo mới phòng ban thành công",
    "hr_app-dpm-s-02": "Cập nhật phòng ban thành công",
    "hr_app-dpm-s-03": "Xóa phòng ban thành công",
    "hr_app-dpm-s-04": "Lấy phòng ban của công ty thành công",
    "hr_app-dpm-f-02-01": "Không tìm thấy phòng ban",
    "hr_app-dpm-f-03-01": "Không tìm thấy phòng ban",
    "hr_app-emp-s-01": "Mời nhân viên mới thành công",
    "hr_app-emp-s-03": "Thêm chủ công ty thành công",
    "hr_app-emp-s-04": "Lấy tất cả nhân viên của công ty thành công",
    "hr_app-emp-s-05": "Lấy tất cả nhân viên của tài khoản thành công",
    "hr_app-emp-s-06": "Cập nhật thông tin nhân viên thành công",
    "hr_app-emp-s-07": "Lấy thông tin nhân viên của bạn thành công",
    "hr_app-emp-s-08": "Cập nhật thông tin nhân viên của tôi thành công",
    "hr_app-emp-f-01-01": "Đã là nhân viên của tôi ty rồi",
    "hr_app-emp-f-02-01": "Mã xác thực không hợp lệ",
    "hr_app-emp-f-02-02": "Đã là nhân viên của tôi ty rồi",
    "hr_app-emp-f-03-01": "Không có quyền thêm chủ công ty",
    "hr_app-emp-f-06-01": "Cập nhật thông tin nhân viên thành công",
    "hr_app-emp-f-07-01": "Không tìm thấy nhân viên",
    "hr_app-emp-f-08-01": "Không tìm thấy nhân viên",
    "hr_app-pos-s-01": "Tạo mới vị trí làm việc thành công",
    "hr_app-pos-s-02": "Cập nhật vị trí làm việc thành công",
    "hr_app-pos-s-03": "Xóa vị trí làm việc thành công",
    "hr_app-pos-s-04": "Lấy vị trí làm việc của công ty thành công",
    "hr_app-pos-f-02-01": "Không tìm thấy vị trí làm việc",
    "hr_app-pos-f-03-01": "Không tìm thấy vị trí làm việc",
    // Project
    "project_app-prj-s-01": "Tạo dự án mới thành công",
    "project_app-prj-s-02": "Cập nhật dự án thành công",
    "project_app-prj-s-03": "Xóa dự án thành công",
    "project_app-prj-s-04": "Lấy dự án của công ty thành công",
    "project_app-prj-s-05": "Thêm thành viên vào dự án thành công",
    "project_app-prj-s-06": "Xỏa bỏ thành viên khỏi dự án thành công",
    "project_app-prj-s-07": "Lấy tất cả dự án của tôi tham gia thành công",
    "project_app-prj-s-08": "Lấy dự án thành công",
    "project_app-prj-s-09": "Cập nhật vai trò thành viên dự án thành công",
    "project_app-prj-f-02-01": "Không tìm thấy dự án",
    "project_app-prj-f-03-01": "Không tìm thấy dự án",
    "project_app-prj-f-05-01": "Không tìm thấy dự án",
    "project_app-prj-f-05-02": "Đã là thành viên của dự án rồi",
    "project_app-prj-f-06-01": "Không tìm thấy dự án",
    "project_app-prj-f-08-01": "Không tìm thấy dự án",
    "project_app-prj-f-09-01": "Không tìm thấy dự án",
    "project_app-task-s-01": "Tạo mới nhiệm vụ thành công",
    "project_app-task-s-02": "Cập nhật nhiệm vụ thành công",
    "project_app-task-s-03": "Xóa nhiệm vụ thành công",
    "project_app-task-s-04": "Lấy tất cả nhiệm vụ của dự án thành công",
    "project_app-task-s-05": "Lấy nhiệm vụ của tôi thành công",
    "project_app-task-s-06": "Cập nhật trạng thái nhiệm vụ thành công",
    "project_app-task-s-07": "Lấy nhiệm vụ thành công",
    "project_app-task-s-08": "Tạo nhiệm vụ phụ thành công",
    "project_app-task-s-09": "Thêm phục thuộc thành công",
    "project_app-task-s-10": "Xóa phụ thuộc thành công",
    "project_app-task-s-11": "Thêm bình luận thành công",
    "project_app-task-s-12": "Sửa bình luận thành công",
    "project_app-task-s-13": "Xóa bình luận thành công",
    "project_app-task-s-14": "Người phụ trách cập nhật nhiệm vụ thành công",
    "project_app-task-f-02-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-03-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-06-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-06-02": "Bạn chỉ được cập nhật nhiệm vụ bạn được giao",
    "project_app-task-f-07-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-08-02":
        "Bạn chỉ được tạo nhiệm vụ phụ cho nhiệm vụ của bạn",
    "project_app-task-f-08-03": "Nhiệm vụ phụ chỉ được 2 cấpt tối đa",
    "project_app-task-f-09-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-09-02": "Không tìm thấy nhiệm vụ phụ thuộc",
    "project_app-task-f-10-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-11-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-12-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-12-02": "Không tìm thấy bình luận",
    "project_app-task-f-12-03": "Bạn chỉ được chỉnh sửa bình luận của mình",
    "project_app-task-f-13-01": "Không tìm thấy nhiệm vụ",
    "project_app-task-f-13-02": "Không tìm thấy bình luận",
    "project_app-task-f-13-03": "Bạn chỉ được xóa bình luận của mình",
    "project_app-task-f-14-01": "Không tìm thấy nhiệm vụ",
};

export default apiCode;
