const apiCode = {
    "global-e-01": "Giá trị không hợp lệ",
    "auth-s-01": "Yêu cầu đăng ký của bạn đã thành công, hãy kiểm tra email",
    "auth-s-02": "Đăng ký thành công",
    "auth-s-03": "Đăng nhập thành công",
    "auth-s-08": "Yêu cầu thành công, hãy kiểm tra email của bạn 📧",
    "auth-s-09": "Lấy lại mật khẩu thành công, chào mừng bại trở lại 👋",
    "auth-e-01": "Email đã tồn tại",
    "auth-e-02": "Email chưa đăng ký",
    "auth-e-03": "Sai mật khẩu",
    "auth-e-04": "Mã code không tìm thấy",
    "auth-e-07": "Mật khẩu hiện tại không đúng",
    "category-s-01": "Thêm category thành công",
    "category-s-02": "Lấy cây category thành công",
    "category-s-03": "Cập nhật category thành công",
    "category-s-04": "Xóa category thành công",
    "category-s-05": "Lấy danh sách attribute thành công",
    "category-s-06": "Thêm attrubute thành công",
    "category-e-01": "Không tìm thấy category",
    "category-e-02": "Không tìm thấy category",
    "category-e-03": "Không tìm thấy category",
    "attribute-s-01": "Thêm attribute thành công",
    "attribute-s-02": "Xóa attribute thành công",
    "attribute-s-03": "Cập nhât attribute thành công",
    "attribute-s-04": "Thêm opption thành công",
    "attribute-e-01": "Không tìm thấy attribute",
    "attribute-option-s-01": "Cập nhật option thành công",
    "attribute-option-s-02": "Xóa option thành công",
    "attribute-option-1-01": "Không tìm thấy option",
    "product-s-09": "Thay đổi trạng thái thành công",
};

export default apiCode;
